apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-eventer.fullname" . }}-agent
  labels:
    {{- include "ai-eventer.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  selector:
    {{- include "ai-eventer.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  ports:
    - port: 8000
      targetPort: 8000
